import { neon } from "@neondatabase/serverless";

type Row = Record<string, unknown>;
type D1Result<T> = { results?: T[]; meta?: { last_row_id?: number } };
type D1Statement = {
  bind: (...values: unknown[]) => D1Statement;
  all: <T>() => Promise<D1Result<T>>;
  run: () => Promise<D1Result<never>>;
};
type D1Database = { prepare: (statement: string) => D1Statement };

let postgresReady: Promise<void> | null = null;

function postgresUrl() {
  return process.env.DATABASE_URL?.trim() || null;
}

async function d1Database(): Promise<D1Database> {
  const moduleName = "cloudflare:workers";
  const workerRuntime = await import(moduleName) as { env?: { DB?: D1Database } };
  if (!workerRuntime.env?.DB) {
    throw new Error("Nenhum banco foi configurado. Na Vercel, adicione DATABASE_URL com a conexão PostgreSQL.");
  }
  return workerRuntime.env.DB;
}

function postgresStatement(statement: string) {
  let index = 0;
  return statement.replace(/\?/g, () => `$${++index}`);
}

async function ensurePostgres() {
  const url = postgresUrl();
  if (!url || postgresReady) return postgresReady;
  postgresReady = (async () => {
    const sql = neon(url);
    const statements = [
      `CREATE TABLE IF NOT EXISTS profiles (
        user_id TEXT PRIMARY KEY,
        email TEXT NOT NULL,
        display_name TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
        updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
      )`,
      `CREATE TABLE IF NOT EXISTS auth_users (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
        updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
      )`,
      `CREATE TABLE IF NOT EXISTS auth_sessions (
        token_hash TEXT PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES auth_users(id) ON DELETE CASCADE,
        expires_at TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
      )`,
      `CREATE INDEX IF NOT EXISTS auth_sessions_user_idx ON auth_sessions(user_id)`,
      `CREATE INDEX IF NOT EXISTS auth_sessions_expiry_idx ON auth_sessions(expires_at)`,
      `CREATE TABLE IF NOT EXISTS transactions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES profiles(user_id) ON DELETE CASCADE,
        type TEXT NOT NULL,
        amount_cents INTEGER NOT NULL,
        description TEXT NOT NULL,
        category TEXT NOT NULL DEFAULT 'Outros',
        transaction_date TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
      )`,
      `CREATE INDEX IF NOT EXISTS transactions_user_date_idx ON transactions(user_id, transaction_date)`,
      `CREATE TABLE IF NOT EXISTS calendar_events (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES profiles(user_id) ON DELETE CASCADE,
        title TEXT NOT NULL,
        event_date TEXT NOT NULL,
        event_time TEXT NOT NULL,
        category TEXT NOT NULL DEFAULT 'Pessoal',
        duration TEXT NOT NULL DEFAULT '1 hora',
        note TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
      )`,
      `CREATE INDEX IF NOT EXISTS calendar_events_user_date_idx ON calendar_events(user_id, event_date)`,
    ];
    for (const statement of statements) await sql.query(statement, []);
  })();
  return postgresReady;
}

export async function queryRows<T extends Row>(statement: string, values: unknown[] = []): Promise<T[]> {
  const url = postgresUrl();
  if (url) {
    await ensurePostgres();
    const sql = neon(url);
    return await sql.query(postgresStatement(statement), values) as T[];
  }
  const database = await d1Database();
  const result = await database.prepare(statement).bind(...values).all<T>();
  return result.results ?? [];
}

export async function runStatement(statement: string, values: unknown[] = []) {
  const url = postgresUrl();
  if (url) {
    await ensurePostgres();
    const sql = neon(url);
    return { rows: await sql.query(postgresStatement(statement), values) as Row[] };
  }
  const database = await d1Database();
  const result = await database.prepare(statement).bind(...values).run();
  return { rows: [] as Row[], lastInsertId: result.meta?.last_row_id };
}
